name: Slack Release Action
on: [push]
jobs:
    slack_upload_job:
        runs-on: ubuntu-latest
        name: Upload release on slack
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: npm i
            - run: npm run build
            - run: ls ${{ github.workspace }}
            - name: List files in the repository
              run: |
                  arr=(releases/*)
                    echo "${arr[0]}"
                    echo "${arr[1]}"
                    echo "${arr[2]}"
                    echo "linux_binary=${arr[0]}" >> $GITHUB_ENV
                    echo "macos_binary=${arr[1]}" >> $GITHUB_ENV
                    echo "windows_binary=${arr[2]}" >> $GITHUB_ENV
                  done
            - name: Upload to slack step
              uses: adrey/slack-file-upload-action@master
              with:
                  token: ${{ secrets.SLACK_TOKEN }}
                  path: ${{ env.windows_binary }}
                  channel: metadata-tool-releases
            - run: echo "Finished. Job's status is ${{ job.status }}."
